set number                                  " Display line number
set linebreak                               " Break lines at word
set showbreak=+++                           " Wrap-broken line prefix
set textwidth=100                           " Line wrap (number of cols)
set showmatch                               " Highlight matching brace
set ruler                                   " Show row and column ruler information

set hlsearch                                " Highlight all search results
set smartcase                               " Enable smart-case search
set ignorecase                              " Always case-insensitive
set incsearch                               " Searches for strings incrementally

set autoindent                              " Auto-indent new lines
set expandtab                               "
set shiftwidth=4                            " Number of auto-indent spaces
set smartindent                             " Enable smart-indent
set smarttab                                " Enable smart-tabs
set softtabstop=4                           " Number of spaces per Tab
set backspace=indent,eol,start	            " Backspace behaviour

call plug#begin('~/.vim/plugged')           " Vim plug start dependancies plugin declaration
Plug 'joshdick/onedark.vim'
Plug 'itchyny/lightline.vim'
Plug 'itchyny/vim-gitbranch'
call plug#end()                             " Vim plug end dependancies plugin declaration

syntax on                                   " Enable symtax coloration
colorscheme onedark                         " Set onedark as vim theme

"One dark specific configurations :
"https://github.com/joshdick/onedark.vim
if (has("termguicolors"))
  set termguicolors
endif

set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'onedark',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'gitbranch#name'
      \ },
      \ }
